config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :profiles do
    delete :remove_show_from_profile
    resources :shows
  end

  get 'select_profile/:profile_id' => 'profiles#select_profile', as: :select_profile

  get '/shows/search' => 'shows#search', as: :show_search

  resources :shows, only: [:index, :show, :create]

  get '/welcome' => 'welcome#index'

  root 'shows#index'

  resources :contacts, only: [:new, :index]

  post '/send_mail' => 'contacts#send_mail'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :shows
  mount_uploader :image, ImageUploader

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async id, key if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform id, key
      painting = Painting.find id
      painting.key = key
      painting.remote_image_url = painting.image.direct_fog_url with_path: true
      painting.save!
      paiting.update_column :image_processed, true
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :current_profile
  before_action :authenticate_user!
  before_action :set_current_profile, only: [:index, :show, :edit]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def profile_shows
    @profile = Profile.find(params[:profile_id])
  end

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = policy_scope(Profile)
    @uploader = Profile.new.image
    @uploader.success_action_redirect = new_profile_url
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new(:key => params[:key])
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        good_change(format, :created)
      else
        bad_change(format, :new)
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        good_change(format, :ok)
      else
        bad_change(format, :edit)
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    session[:profile_id] = nil
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_profile
    session[:profile_id] = params[:profile_id]
    redirect_to profile_shows_path session[:profile_id]
  end

  def remove_show_from_profile
    @profile = Profile.find(params[:profile_id])
    show = Show.find(params[:format])
    @profile.shows.delete show
    redirect_to @profile
  end

  def set_current_profile
    @current_profile ||= Profile.find(session[:profile_id])
  rescue ActiveRecord::RecordNotFound
    @current_profile = nil
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params[:profile][:show_ids] = params[:profile][:show_ids].split if params[:profile][:show_ids]
    params.require(:profile).permit(:name, :image, :remote_image_url, :key, show_ids: [])
  end

  def good_change(format, status)
    session[:profile_id] = @profile.id
    format.html { redirect_to @profile, notice: 'Profile was successfully changed.' }
    format.json { render :show, status: status, location: @profile }
  end

  def bad_change(format, status)
    format.html { render status }
    format.json { render json: @profile.errors, status: :unprocessable_entity }
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="clearfix">
    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar1.png"), :pic => "1", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar2.png"), :pic => "2", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar3.png"), :pic => "3", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar4.png"), :pic => "4", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar5.png"), :pic => "5", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar6.png"), :pic => "6", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar7.png"), :pic => "7", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar8.png"), :pic => "8", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar9.png"), :pic => "9", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar10.png"), :pic => "10", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>
  </div>

  <%= f.hidden_field :image_url, :id => 'profile-pic',:value => "avatars/avatar-blank.png" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_index_form.html.erb
<%= form_for(@current_profile) do |f| %>
  <% if @current_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
      <% @current_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="clearfix">
    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar1.png"), :pic => "1", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar2.png"), :pic => "2", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar3.png"), :pic => "3", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar4.png"), :pic => "4", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_url("avatars/avatar5.png"), :pic => "5", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar6.png"), :pic => "6", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar7.png"), :pic => "7", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar8.png"), :pic => "8", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar9.png"), :pic => "9", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>

    <div class="profile-pic chooser rounded">
      <%= image_tag asset_path("avatars/avatar10.png"), :pic => "10", :class => 'rounded' %>
      <input type="checkbox" class="profile_checkbox">
    </div>
  </div>

  <%= f.hidden_field :image_url, :id => 'profile-pic',:value => "avatars/avatar-blank.png" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>


<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<section class="settings">
  <section class="grey">

    <% @profiles.each do |profile| %>
    <section class="twelve columns profile">
      <%= link_to select_profile_path(profile) do %>
        <% if profile.image_url %>
          <%= image_tag asset_path(profile.image_url), :class => 'rounded' %>
        <% else %>
          <%= image_tag asset_path('avatars/avatar-blank.png'), :class => 'rounded' %>
        <% end %>
      <% end %>
      <h1 class="h1profile">Profile Info</h1>
      <h2 class='profile_name'>Current:</h2>
        <p><%= profile.name.capitalize %></p>
      <h2>Add new profile</h2>
      <form>
        <input class="field">
        <button class="add_button">Add</button>
      </form>
    </section>
    <div class="clear">&nbsp;</div>
    <%= link_to 'Edit', edit_profile_path(profile), :class => 'button' %>
    <%= link_to 'Delete', profile, method: :delete, :class => 'button', data: { confirm: 'Do you want to delete this profile?' } %>
    <% end %>
  </section>
  <section class="options">
    <h1>Profile Options</h1>
    <%= render 'index_form' %>
  </section>
  <section class="grey">
    <h1>Password Change</h1>
  </section>
  <section>
    <h1>Delete Profile</h1>
  </section>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/profile_shows_index.html.erb
<div id="calendar__container" class="tracker_form_wrapper clearfix">
  <div class="calendar__slideshow_nav">
    <div>
      <%= image_tag 'left_arrow.png', :class => 'calendar__show_slider_left opacity6' %>
    </div>
    <div>
      <%= image_tag 'right_arrow.png', :class => 'calendar__show_slider_right opacity6' %>
    </div>
  </div>

  <div class="calendar__hider">
    <div class="calendar__titles">
      <div class="calendar__spacer">
        <p class="calendar__title--header">SHOWS</p>
      </div>
      <% @profile.shows.each do |show| %>
        <%= link_to show_path(show) do %>
          <%= image_tag show.banner, :class => 'calendar__banner' %>
        <% end %>
      <% end %>
    </div>
    <section id="calendar__no-shows" class="calendar__no-shows-text">
      <h1>You have no shows selected. Select some shows to track from the Browse page.</h1>
    </section>
    <div id="calendar__slideshow">
      <div class='calendar__row clearfix'>
        <% (0..60).each do |day| %>
          <div class="head calendar__item">
            <%= (Date.today + day).strftime("%a %e") %>
          </div>
        <% end %>
      </div>

      <% @profile.shows.each do |show| %>
        <% episodes = show.episodes %>

        <div class='calendar__row clearfix'>
          <% (0..60).each do |day| %>
            <% if playing_on?(Date.today + day, episodes) %>
              <div class="time calendar__item full">
            <% else %>
              <div class="time calendar__item empty">
            <% end %>
              <%= show.air_time if playing_on?(Date.today + day, episodes) %>
            </div>
          <% end %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<section class="">
  <%= link_to edit_profile_path @profile do %>
    <%= image_tag asset_path(@profile.image_url), class: "profile_pic sm right rounded" %>
  <% end %>
  <h2>Your Shows</h2>
  </section>
<section class="clearfix thirteen columns">
    <% @profile.shows.each do |show| %>
    <section class="four columns">
      <%= link_to show_path(show), class: 'columns relative' do %>
        <%= image_tag show.poster, class: "fixer" %>
        <%= image_tag 'plusbutton.png', :class => 'plus_sign2' %>
        <%= link_to show_path(show), class: 'four columns' do %>
        <% end %>
      <% end %>
      <div>
<%= link_to 'X Remove Show', profile_remove_show_from_profile_path(@profile, show),:class => 'delete_show', :method => :delete %>
      </div>
    </section>
  <% end %>
<div class="clear">&nbsp;</div>