config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :profiles do
    delete :remove_show_from_profile
    resources :shows
  end

  get 'select_profile/:profile_id' => 'profiles#select_profile', as: :select_profile

  get '/shows/search' => 'shows#search', as: :show_search

  resources :shows, only: [:index, :show, :create]

  get '/welcome' => 'welcome#index'

  root 'shows#index'

  resources :contacts, only: [:new, :index]

  post '/send_mail' => 'contacts#send_mail'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def new
    @contact = Contact.new
  end

  def send_mail
    name = params[:name]
    email = params[:email]
    message = params[:message]
    ContactMailer.delay.contact_email(name, email, message)
    redirect_to contacts_path, notice: 'Your message has been sent!'
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="container-content text-center">
  <% flash.each do |key, value| %>
    <h2><%= value %></h2>
  <% end %>
  <%= link_to 'Home', root_path %>
</div>

app/views/contacts/new.html.erb
<section class="tracker_form_wrapper">
  <h2>Want to send us a message?</h2>
  <h1>Contact Us</h1>
    <%= form_tag(send_mail_path) do %>
      <div class="field">
        <%= label_tag 'name', 'Name' %><br />
        <%= text_field_tag 'name', nil, class: '', placeholder: 'Your Name' %>
      </div>
      <div class="field">
        <%= label_tag 'email', 'Email' %><br />
        <%= email_field_tag 'email', nil, class: '', placeholder: 'Your Email Address' %>
      </div>
      <div class="field">
        <%= label_tag 'message', 'Message' %><br />
        <%= text_area_tag 'message', nil, class: 'tracker_form_wrapper__text-box-large', rows: 6, placeholder: 'Enter message here...' %>
      </div>
      <div class="actions">
        <%= submit_tag 'Submit', class: '' %>
      </div>
    <% end %>
</div>