config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :profiles do
    delete :remove_show_from_profile
    resources :shows
  end

  get 'select_profile/:profile_id' => 'profiles#select_profile', as: :select_profile

  get '/shows/search' => 'shows#search', as: :show_search

  resources :shows, only: [:index, :show, :create]

  get '/welcome' => 'welcome#index'

  root 'shows#index'

  resources :contacts, only: [:new, :index]

  post '/send_mail' => 'contacts#send_mail'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :shows
  mount_uploader :image, ImageUploader

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async id, key if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform id, key
      painting = Painting.find id
      painting.key = key
      painting.remote_image_url = painting.image.direct_fog_url with_path: true
      painting.save!
      paiting.update_column :image_processed, true
    end
  end
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_and_belongs_to_many :profiles
  serialize :episodes

  def update_episodes
    show = TVDB.get_series_by_id(self.series_id)
    self.episodes = show.episodes.last(20)
    self.save
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :show, :new, :create]
  # GET /shows
  # GET /shows.json
  def index
    @profile = current_profile
    if params[:profile_id] # if profile
      @shows = ShowPolicy::Scope.new(current_profile, Show).resolve
      render '/profiles/profile_shows_index' # goto Profile/shows (calendar)
    else
      @shows = Show.all # go to all shows
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])
    if session[:profile_id]
      @profile = Profile.find(session[:profile_id])
    end
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = build_show
    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    results = TVDB.search(params["search-bar__text-box".to_sym])
    @shows = results.reject { |show| show["SeriesName"] == "** 403: Series Not Permitted **" }.map { |show| show }
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def show_params
    params.require(:show).permit(:name, :air_time, :status, :next_episode, :overview, :banner, :poster)
  end

  def build_show
    show = TVDB.get_series_by_id(params[:series_id])
    Show.new(name: show.name, air_time: show.air_time, status: show.status,
             episodes: show.episodes.last(20),
             banner: get_banner(show),
             poster: get_poster(show),
             overview: show.overview)
  end

  def get_banner(show)
    return "" if show.series_banners('en').first.nil?
    show.series_banners('en').first.url
  end

  def get_poster(show)
    return "" if show.posters('en').first.nil?
    show.posters('en').first.url
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :air_time %><br>
    <%= f.text_field :air_time %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :next_episode %><br>
    <%= f.text_field :next_episode %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
  <div class="field">
    <%= f.label :banner %><br>
    <%= f.text_field :banner %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form' %>


<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
  <section class="thirteen columns">
    <% @shows.each do |show| %>
        <%# link_to show_path(show), class: 'poster-link four columns' do %>
          <!-- <img class="poster" src="<%= show.poster %>"> -->
          <%# image_tag 'plusbutton.png', :class => 'plus_sign' %>
        <%# end %>
        <%= link_to show_path(show), class: 'poster-link four columns' do %>
          <img class="poster" src="<%= show.poster %>">
          <%= image_tag 'plusbutton.png', :class => 'plus_sign' %>
        <% end %>
        <% if @profile != nil %>
          <%= form_for @profile, remote: true do |f| %>
            <%= f.hidden_field :show_ids, value: @profile.show_ids << show.id %>

          <% end %>
        <% end %>
    <% end %>
  </section>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/search.html.erb
<section class="search_section">
<% if @shows.empty? %>
  <h1>No Search Results. Please try again.</h1>
<% else %>



  <% @shows.each do |show| %>
    <div class="search_show">
      <% if Show.exists?(:name => show["SeriesName"]) %>
          <%= link_to show["SeriesName"], show_path(Show.where(:name => show["SeriesName"]).first.id), class: "search_title" %>
        <% else %>
          <%= link_to show["SeriesName"], shows_path(series_id: show["seriesid"]), :method => :post, class: "search_title" %>
        <% end %>

      <p>
        <%= show["Overview"] %>
      </p>

    </div>
  <% end %>

<% end %>

<%= link_to "Back", :back %>
</section>

app/views/shows/show.html.erb
<section class="grey">


<img src="<%= @show.poster %>" class="one-third column">
<section class="show_info eight columns">
<h1 class="poster_name">
  <%= @show.name %>
</h1>
<p>
  <strong>Status:</strong>
  <%= @show.status %>
</p>

<% if @show.air_time %>
  <p>
    <strong>Air time:</strong>
    <%= @show.air_time %>
  </p>
  <p>
    <strong>Next episode:</strong>
    <%= current_next_episode(@show.episodes) %>
  </p>
<% end %>

<p>
  <strong>Overview:</strong>
  <%= @show.overview %>
</p>

<% if @profile %>
  <%= form_for @profile, remote: true, html: { id: "show-show-form"} do |f| %>
    <%= f.hidden_field :show_ids, value: @profile.show_ids << @show.id %>
    <%= f.submit "Track Show" %>
  <% end %>
<% else %>
  <%= button_to "Track Show", new_user_registration_path, :method => :get  %>
<% end %>
</section>
<div class='clear'>
</section>