config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :profiles do
    delete :remove_show_from_profile
    resources :shows
  end

  get 'select_profile/:profile_id' => 'profiles#select_profile', as: :select_profile

  get '/shows/search' => 'shows#search', as: :show_search

  resources :shows, only: [:index, :show, :create]

  get '/welcome' => 'welcome#index'

  root 'shows#index'

  resources :contacts, only: [:new, :index]

  post '/send_mail' => 'contacts#send_mail'
end

app/views/layouts/_footer.html.erb
<footer class="twelve columns">
    <p>&copy Copyright 2015 CodeFellows TV Tracker</p>
</footer>

app/views/layouts/_header.html.erb
<div class="profile-links">
  <nav>
  <%= link_to "Shows", shows_path, :class => "" %>
    <ul>
      <li><%= link_to "Browse", shows_path %></li>
      <li><%= link_to "My Shows", profile_path(@current_profile) %></li>
      <li><%= link_to "Calendar", profile_shows_path(@current_profile) %></li>
    </ul>
  </nav>

  <nav>
    <%= link_to "Settings", profiles_path, :class => "xs-text-left sm-text-center" %>
    <ul>
      <li><%= link_to "Profiles", profiles_path %></li>
      <li><%= link_to "Preferences", edit_user_registration_path %></li>
    </ul>
  </nav>
</div>

<div class="">
  <%= form_tag show_search_path, :method => 'get' do %>
    <%= text_field_tag :Search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

app/views/layouts/_sign_in.html.erb
<%= content_tag :div, class: "sign_in_nav col-xs-12 col-md-3" + (user_signed_in? ? " col-sm-2" : " col-sm-4") do %>
  <nav class="sign_in_nav xs-text-center sm-text-right">
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "full" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "half" %>
      <%= link_to "Sign In", new_user_session_path, class: "half" %>
    <% end %>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TvTracker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: "" + " "+(current_page?(root_url) ? "home" : "" ) do %>
    <input type="checkbox" id="nav-trigger" class="nav-trigger" />
    <label id="nav-trigger-label" for="nav-trigger">MENU</label>
      <ul class="navigation">
        <li class="nav-item">
          <% if current_user %>
           <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign Up / Log In", new_user_registration_path %>
          <% end %>
        </li>
        <li class="nav-item"><%= link_to "Browse", shows_path %></li>
        <li class="nav-item">
          <% if @profile != nil && @profile.id != nil %>
            <%= link_to "My Shows", profile_path(@current_profile) %>
          <% else %>
            <%= link_to "My Shows", new_user_registration_path %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if @profile != nil && @profile.id != nil %>
            <%= link_to "Settings", profiles_path %>
          <% else %>
            <%= link_to "Settings", new_user_registration_path %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if @profile != nil && @profile.id != nil %>
          <%= link_to "Calendar", profile_shows_path(@current_profile) %>
          <% else %>
          <%= link_to "Calendar", new_user_registration_path %>
          <% end %>
       </li>
        <li class="nav-item"><%= link_to "Contact", new_contact_path %></li>
      </ul>
  <div class="site-wrap clearfix container">
    <header class= "twelve columns newbanner">
        <%= link_to root_path, class: '' do %>
          <%= image_tag 'TvTrackerLogo.png', :class => 'logo' %>
        <% end %>
      <section class="search-bar">
        <div class="search-bar__wrapper">
          <%= form_tag show_search_path, :method => 'get' do %>
            <label class="search-bar__text-box--label" labelFor="search-bar__text-box">SEARCH</label>
            <%= text_field_tag "search-bar__text-box", params[:search], placeholder: "Enter search term...", class: "search-bar__text-box--input" %>
          <% end %>
        </div>
      </section>
    </header>
    <main class="twelve columns">
      <%= content_tag :section, class: "content_here" do %>
        <%= yield %>
      <% end %>
    </main>
        <%= render 'layouts/footer' %>
      <% end %>
  </div>
</body>
</html>